### ISSUE TITLE
Deprecate/Extract from {Static,}Object / Shallow Class Hierachy

### ISSUE THREAD

**Issue by mariuswilms** [UnionOfRAD/lithium#1251]
We aim to remove core base classes (Object and StaticObject) to flatten class hierarchy. The second goal is to ensure we don't run into future name collision once PHP decides to make Object a reserved name.
- [x] Deprecate invokeMethod() if possible by replacing usage with $this binding to closures, if not possible extract into trait (#1211 already has some refactorings regarding this). (@davidpersson assigned)
- [x] Fix failing tests relying on `invokeMethod()`
- [x] Extract autoConfig into Trait method,
- [x] Move `_instance()` somewhere else TBD i.e. into Libraries::instance(), Note: some classes (Model, Create Command) have their own _instance implemenations
- [x] Extract filter functionality, merge #1211
- [x] Check where parents() is used and make it available as a trait to theses classes.
- [x] Deprecate __set_state, and find other ways to test by modifying tests
- [x] Move stop() into Command and ErrorHandler. Then deprecate. Patch: #1256.
- [x] Deprecate respondsTo? Is used only in one place (excl. tests)
- [ ] Classes which rely on auto configuration currently present in the base class' `_init()` should make use of `AutoConfigurable` instead. 
- [ ] Deprecate `_init()`, where tests rely on skipping the initialization phase, change classes to accept an alternative less-generically named option to skip certain parts of the initialization phase. The `_init()` class methods will than need to be merged into the constructor.

**Comment by alexbowers** [comment]
https://github.com/UnionOfRAD/lithium/pull/1256 references point 7 (Move stop() into Command and ErrorHandler. Then deprecate.)

**Comment by alexbowers** [comment]
@davidpersson How do you see autoConfig being refactored?

**Comment by davidpersson** [comment]
Good question. It's a bit complicated to get this clean and right.

**Comment by davidpersson** [comment]
I've did some more work on the topic and will push a branch shortly. It turns out this will be a more or less significant change and would add too much to the 1.1 release. As these changes are not strictly required for PHP7 compatibility (Object is "just" soft reserved), I'm rerouting it to the 1.2 milestone. I want to keep the psychological barrier as low as possible for everybody to upgrade to the next minor version.

**Comment by davidpersson** [comment]
I've pushed the current state of work into the struct/deprecate branch. This allows us continuing working together on this change.

https://github.com/UnionOfRAD/lithium/tree/struct/deprecate-object

**Comment by davidpersson** [comment]
Also see updated issue description on the top for pending tasks.

**Comment by niel** [comment]
Is the reference to `AutoConfiguration` at the top, supposed to be a class (which I can't find) or to the trait `AutoConfigurable`?

**Comment by davidpersson** [comment]
It was supposed to be a reference to the trait, I've fixed the typo in the issue text.

**Comment by mariuswilms** [comment]
For 1.2 we're going without finishing the changes to or removal of of `_init()`, `$_config`, auto-configuration. This will be finished in 2.0.

**Comment by mariuswilms** [comment]
The finalization phase of this issue for 2.0 continues in the `init-removal` branch.

**Comment by mariuswilms** [comment]
Closing, 2.0 work continues in #1341
